LOGIN_STEAM = ''
PASSWORD_STEAM = ''
STEAMID = 0

INPUT_TXT_FILE_PATH = './data/input.txt'
OUTPUT_TXT_FILE_PATH = './data/output.txt'
PATH_TO_LOGS = './logs/'

PAINTWEAR_QUALITY_RANGE_LIST = [
    [0.15, 0.18],
    [0.18, 0.21],
]

PERCETAGE_FROM_REFERENCE_PRICE = 0.15 # 15%